name: nuwa_navigation_app
description: A Flutter Windows app to run robot navigation flow.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  share_plus: ^10.1.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.2
  # JSON 序列化 / 反序列化
  json_annotation: ^4.9.0
  # 狀態管理 (簡單用 provider 就好)
  provider: ^6.1.2
  # UUID (產生隨機 uId 也可用)
  uuid: ^4.5.1
  # 日期時間格式 (產 missionId 用)
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
